apiVersion: v2
name: generic
description: Generic helm chart for all kind of applications

type: application
version: 0.1.1

keywords:
  - java
  - node
  - dotnet
  - kubernetes
  - stakater
  - application

home: https://github.com/devopshobbies/helm-generic
maintainers:
  - name: Ahmad Ali Bagheri
    email: ahmad@devopshobbies.com

  - name: Mehdi Rahimi
    email: mediraworkm@gmail.com

icon: https://github.com/stakater/ForecastleIcons/blob/master/stakater.png
